name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [ kernel-update ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 安装 Python 2.7（通过旧版 .deb 包）
      - name: Install Python 2.7 from old Ubuntu repo
        run: |
          sudo apt update
          sudo apt install -y wget
          wget http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-minimal_2.7.18-13ubuntu1.2_amd64.deb
          wget http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7-minimal_2.7.18-13ubuntu1.2_amd64.deb
          wget http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-stdlib_2.7.18-13ubuntu1.2_amd64.deb
          wget http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7_2.7.18-13ubuntu1.2_amd64.deb
          sudo apt install ./libpython2.7-minimal_*.deb ./python2.7-minimal_*.deb ./libpython2.7-stdlib_*.deb ./python2.7_*.deb
          sudo ln -sf /usr/bin/python2.7 /usr/bin/python

      - name: Build
        run: |
          sudo apt update
          sudo apt install android-tools-mkbootimg bc build-essential ca-certificates cpio curl git kmod libssl-dev libtinfo5 sudo unzip wget xz-utils -y --no-install-recommends
          ./build.sh

      - name: Upload basic tarball with boot and recovery images
        uses: actions/upload-artifact@v4
        with:
          path: out/*

  flashable:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      # 安装 Python 2.7（通过旧版 .deb 包）
      - name: Install Python 2.7 from old Ubuntu repo
        run: |
          sudo apt update
          sudo apt install -y wget
          wget http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-minimal_2.7.18-13ubuntu1.2_amd64.deb
          wget http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7-minimal_2.7.18-13ubuntu1.2_amd64.deb
          wget http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-stdlib_2.7.18-13ubuntu1.2_amd64.deb
          wget http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7_2.7.18-13ubuntu1.2_amd64.deb
          sudo apt install ./libpython2.7-minimal_*.deb ./python2.7-minimal_*.deb ./libpython2.7-stdlib_*.deb ./python2.7_*.deb
          sudo ln -sf /usr/bin/python2.7 /usr/bin/python

      - name: Make OTA images
        run: |
          sudo apt update
          sudo apt install -y img2simg jq sudo wget xz-utils
          DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
          ./build/fetch-and-prepare-latest-ota.sh "16.04/arm64/android9/devel" "$DEVICE" ota
          mkdir -p out/
          ./build/system-image-from-ota.sh ota/ubuntu_command out

      - uses: actions/upload-artifact@v4
        with:
          name: OTA images
          path: |
            out/boot.img
            out/system.img
            out/recovery.img
